language: java
sudo: true
dist: trusty
jdk: openjdk8
install:
- true
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
  - chmod +x mvnw
addons:
  postgresql: "9.5" // change "9.5" for your postgres specific version
services:
- postgresql
deploy:
 provider: heroku
 api-key:
  secure: 0a47ec9f-7d68-4bbe-835f-51fac74cbc17
 app: YourScheduleSpringRU