language: java
jdk: openjdk8

env:
  - MAVEN_VERSION=4.0.0

install:
    - mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}

script: ./mvnw --show-version --errors --batch-mode -Prun-its clean verify